### PR TITLE
add C17, C23, C++20, C++23 language standards

### PR DESCRIPTION
**Pull request by bitrunner**
Greetings!

I'd like to help you resurrect CND.

This pull request adds C17, C23, C++20, and C++23 language standards. This only seems useful for netbeans managed makefile projects. I tested by making a new simple project and changing the standard and observing the build output on Linux with GCC 13.2.0 contains the expected compiler flags to enforce the selected standard.  I didn't find any relevant unit tests to update for this and existing tests I tried still passed, but there might be something I overlooked somewhere.

This is my first foray into netbeans development so there might be something really dumb in here or things I overlooked.

I didn't mess with any of the language tokenization cruft related to the language standards as that seems obsolete due to your LSP work.

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @bitrunner ,

Looks correct to me, but I'll take a deeper look when I have some free time to spend on the NetBeans CND branch. This may take me some weeks, though.

Thanks for the PR!

**Comment by bitrunner** [comment]
Does it makes more sense for me to open these pull requests against the cnd branch at https://github.com/apache/netbeans?  I thought your CND work hadn't been merged there yet, but maybe that's got enough for me to contribute there without making too big of a mess for you?

**Comment by vieiro** [comment]
Hi @bitrunner ,

I think it's a good idea for you to join the NetBeans DEV mailing list (https://netbeans.apache.org/community/mailing-lists.html#dev) and discuss there that you're interested in pushing the CND effort forward. Doing pushes to the Apache repository is preferred: there're more CI/CD controls and tools for quality/tests that are disabled in this repo.

Currently `cnd-next` has the `cpplite` module disabled, because it clashes with CND. This is something that has to be discussed in the mailing list (we may let the user disable `cpplite` in favor of `cnd` as well).

Thanks,
Antonio

**Comment by bitrunner** [comment]
Copy.  I'll close these pull requests here and open them against netbeans proper.  I followed the mailing list discussion last year regarding how to move forward with cnd and cpplite.  There seemed to be some ideas.

**Pull request closed without merging**
